#!/usr/bin/env bash
# generate-secrets.sh — Generate a ready-to-use .env for ChipAtelier
# Usage: bash scripts/generate-secrets.sh > .env
#        bash scripts/generate-secrets.sh  (writes .env in place, backs up existing)
#
# Requires: openssl (pre-installed on virtually every Linux/macOS)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"

# ── helpers ──────────────────────────────────────────────────────────────────
gen_hex()   { openssl rand -hex "$1"; }           # $1 bytes → hex string (2x chars)
gen_b64()   { openssl rand -base64 "$1" | tr -d '=+/\n' | head -c "$2"; }
gen_alnum() { openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c "$1"; }

# ── generate values ───────────────────────────────────────────────────────────
POSTGRES_PASSWORD=$(gen_hex 24)           # 48-char hex
JWT_SECRET_KEY=$(gen_hex 32)              # 64-char hex  (HS256 key)
VNC_TOKEN_SECRET=$(gen_hex 32)            # 64-char hex  (HMAC signing)
MINIO_ACCESS_KEY=$(gen_alnum 20)          # 20 alphanumeric (like AWS key ID)
MINIO_SECRET_KEY=$(gen_alnum 40)          # 40 alphanumeric (like AWS secret)

# ── write .env ────────────────────────────────────────────────────────────────
if [ -t 1 ] && [ -f "$ENV_FILE" ]; then
  # Running interactively and .env already exists — back it up
  BACKUP="$ENV_FILE.bak.$(date +%Y%m%d%H%M%S)"
  cp "$ENV_FILE" "$BACKUP"
  echo "# Backed up existing .env → $BACKUP" >&2
fi

cat > "$ENV_FILE" <<EOF
# ChipAtelier — generated by scripts/generate-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# NEVER commit this file to git.

# ── PostgreSQL ────────────────────────────────────────────────────────────────
POSTGRES_USER=chipatelier
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=chipatelier

# Database URL (matches compose service name "postgres")
DATABASE_URL=postgresql+asyncpg://chipatelier:${POSTGRES_PASSWORD}@postgres:5432/chipatelier

# ── Redis ─────────────────────────────────────────────────────────────────────
REDIS_URL=redis://redis:6379/0

# ── MinIO (S3-compatible local storage) ───────────────────────────────────────
STORAGE_BACKEND=minio
MINIO_ENDPOINT=minio:9000
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
S3_BUCKET_ARTIFACTS=chipatelier-artifacts

# ── Auth ──────────────────────────────────────────────────────────────────────
JWT_SECRET_KEY=${JWT_SECRET_KEY}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=7
VNC_TOKEN_SECRET=${VNC_TOKEN_SECRET}

# ── Storage paths ─────────────────────────────────────────────────────────────
# Set DATA_ROOT to your preferred storage mount before running docker compose up.
# Run scripts/install.sh after setting these to create required directories.
DATA_ROOT=/opt/apps/chipatelier/data
WORKSPACE_ROOT=/tmp/chipatelier_workspaces

# ── OpenROAD ──────────────────────────────────────────────────────────────────
ORFS_IMAGE=openroad/orfs:latest
ARTIFACTS_ROOT=/data/artifacts
WARM_POOL_SIZE=2
MAX_CONCURRENT_JOBS=8
JOB_TIMEOUT_SECONDS=7200

# ── Resource limits per student job ───────────────────────────────────────────
JOB_CPU_CORES=6
JOB_RAM_GB=8
JOB_DISK_GB=5

# ── VNC session limits ────────────────────────────────────────────────────────
MAX_VNC_SESSIONS=4

# ── Worker concurrency ────────────────────────────────────────────────────────
ORFS_WORKER_CONCURRENCY=4
BACKGROUND_WORKER_CONCURRENCY=2

# ── AI Service ────────────────────────────────────────────────────────────────
# Reuse the existing di_ollama service already running on this server.
# "host-gateway" is added to backend/worker extra_hosts so they can reach it.
LLM_BACKEND=ollama
OLLAMA_BASE_URL=http://host.docker.internal:11434
ANTHROPIC_API_KEY=

# ── Domain ────────────────────────────────────────────────────────────────────
# Update to match your hostname or IP when deploying behind a reverse proxy.
ALLOWED_ORIGINS=http://localhost:8080
EOF

echo "✓ .env written to $ENV_FILE" >&2
echo "" >&2
echo "  POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}" >&2
echo "  JWT_SECRET_KEY    : ${JWT_SECRET_KEY}" >&2
echo "  VNC_TOKEN_SECRET  : ${VNC_TOKEN_SECRET}" >&2
echo "  MINIO_ACCESS_KEY  : ${MINIO_ACCESS_KEY}" >&2
echo "  MINIO_SECRET_KEY  : ${MINIO_SECRET_KEY}" >&2
echo "" >&2
echo "Next: review .env, then run:  docker compose up -d --build" >&2
